### ISSUE TITLE
Instructions say to cabal install, but no cabal file is present?

### ISSUE THREAD

**Issue by peterstorm** [alogic0/lucid-from-html#19]
Hello!

Trying to test this out, but instructions are unclear.

Says to `cabal install` but no cabal file is present?

**Comment by alogic0** [comment]
Hi @peterstorm ,
You are right, README is somewhat outdated. To generate _.cabal_ file you need to run **hpack** command in the source directory. Because _.cabal_ in this process is a produced file, it hasn't been included in the source.
http://typeful.net/talks/hpack/#6

**Comment by alogic0** [comment]
Closed with [9952b91](https://github.com/alogic0/lucid-from-html/commit/9952b916080dcd375eeb0aa95a95f6ec45b50d82#diff-04c6e90faac2675aa89e2176d2eec7d8)
