### ISSUE TITLE
Support for lucid2

### ISSUE THREAD

**Issue by sigrdrifa** [alogic0/lucid-from-html#20]
Thanks for this amazing library! Just a question, have you looked into supporting lucid2? 

https://hackage.haskell.org/package/lucid2 

I think it is similar but has some distinct differences

**Comment by alogic0** [comment]
Hi, @sigrdrifa! Unfortunately, I'm not actively developing this library anymore, so I welcome any forks :) Will be good practice in Haskell.

**Comment by sigrdrifa** [comment]
Thanks! Already forked and made it work with Lucid2 :)
